branches:
  only:
  - master

environment:
  nodejs_version: '5.2.0'

install:
  - ps: Install-Product node $env:nodejs_version
  - choco install yarn
  - refreshenv
  - set CI=true
  - set PATH=%APPDATA%\npm;%PATH%
cache:
 - "%LOCALAPPDATA%/Yarn"

build: off
version: '{build}'
shallow_clone: true
clone_depth: 1

test_script:
  - node --version
  - npm --version
  - npm test
